DROP USER IF EXISTS 'mangos'@'%';
CREATE USER 'mangos'@'%' IDENTIFIED BY 'mangos' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0;
GRANT ALL PRIVILEGES ON * . * TO 'mangos'@'%' WITH GRANT OPTION;
